In [45]:
import pandas as pd

In [46]:
moves = pd.read_csv('moves.csv')
pokemon_moves = pd.read_csv('pokemon_moves.csv')
pokemon_stats = pd.read_csv('pokemon_stats.csv')
pokemon_types = pd.read_csv('pokemon_types.csv')
pokemon = pd.read_csv('pokemon.csv')
stats = pd.read_csv('stats.csv')
type_efficacy = pd.read_csv('type_efficacy.csv')
types = pd.read_csv('types.csv')


pokemon

,id,identifier,species_id,height,weight,base_experience,order,is_default
0,1,bulbasaur,1,7,69,64.0,1.0,1
1,2,ivysaur,2,10,130,142.0,2.0,1
2,3,venusaur,3,20,1000,263.0,3.0,1
3,4,charmander,4,6,85,62.0,5.0,1
4,5,charmeleon,5,11,190,142.0,6.0,1
...,...,...,...,...,...,...,...,...
1297,10273,ogerpon-wellspring-mask,1017,12,398,NaN,NaN,0
1298,10274,ogerpon-hearthflame-mask,1017,12,398,NaN,NaN,0
1299,10275,ogerpon-cornerstone-mask,1017,12,398,NaN,NaN,0
1300,10276,terapagos-terastal,1024,3,160,NaN,NaN,0
1301,10277,terapagos-stellar,1024,17,770,NaN,NaN,0

In [47]:
index = 1

oponente = pokemon[pokemon['id'] == index]


#DEFINIDO O TIPO MAIS EFICAZ CONTRA O OPNENTE
types_oponente = pokemon_types[pokemon_types['pokemon_id']
                               == index]['type_id'].values

if len(types_oponente) > 1:
    # Se houver dois tipos de ataque eficazes contra o oponente
    types_ataque = type_efficacy[(type_efficacy['target_type_id'] == types_oponente[0]) | (
        type_efficacy['target_type_id'] == types_oponente[1])]
else:
    # Se houver apenas um tipo de ataque eficaz contra o oponente
    types_ataque = type_efficacy[type_efficacy['target_type_id'] == types_oponente[0]]

types_ataque = types_ataque[types_ataque['damage_factor'] == 200]
count_targets = types_ataque.groupby('damage_type_id')['target_type_id'].nunique()
multi_target_damage = count_targets[count_targets > 1].values


if len(multi_target_damage) == 0:
    type_most_eficaz = types_ataque.iloc[0]['damage_type_id']
else:
    type_most_eficaz = multi_target_damage[0]



type_most_eficaz

3

In [48]:
oponente_stats = pokemon_stats[pokemon_stats['pokemon_id'] == index]


# id,damage_class_id,identifier,is_battle_only,game_index
# 1,,hp,0,1
# 2,2,attack,0,2
# 3,2,defense,0,3
# 4,3,special-attack,0,5
# 5,3,special-defense,0,6
# 6,,speed,0,4
# 7,,accuracy,1,
# 8,,evasion,1,

defense_op = pd.concat([
    oponente_stats[oponente_stats['stat_id'] == 3],
    oponente_stats[oponente_stats['stat_id'] == 5]
]).sort_values(by='base_stat', ascending=False)

worst_denfese_op = defense_op.iloc[0]['stat_id']
best_attack = 2 if worst_denfese_op == 3 else 4

In [49]:
# id,identifier
# 1,status
# 2,physical
# 3,special


moves = moves[moves['damage_class_id'] != 1]

moves = moves[moves['type_id'] == type_most_eficaz]
if worst_denfese_op == 3:
    moves = moves[moves['damage_class_id'] == 2]
if worst_denfese_op == 5:
    moves = moves[moves['damage_class_id'] == 3]

moves = moves.sort_values(by=['power', 'accuracy'], ascending=False)


golpe_most_power = moves.iloc[0]

golpe_most_power

id                               542
identifier                 hurricane
generation_id                      5
type_id                            3
power                          110.0
pp                              10.0
accuracy                        70.0
priority                           0
target_id                         10
damage_class_id                    3
effect_id                      334.0
effect_chance                   30.0
contest_type_id                  NaN
contest_effect_id                NaN
super_contest_effect_id          NaN
Name: 541, dtype: object

In [50]:
pokemon_possibles = pokemon_moves[pokemon_moves['move_id']
                                  == golpe_most_power['id']]

pokemon_possibles = pokemon_possibles[pokemon_possibles['version_group_id'] == 25]

pokemon_possibles

pokemon_possibles_stats = pokemon_stats[pokemon_stats['stat_id'] == best_attack]
pokemon_possibles_stats = pokemon_stats[pokemon_stats['stat_id'] == best_attack]


pokemon_possibles_stats = pokemon_possibles_stats[pokemon_possibles_stats['pokemon_id'].isin(
    pokemon_possibles['pokemon_id'])]

pokemon_possibles_stats = pokemon_possibles_stats.sort_values(by='base_stat', ascending=False)

best_pokemon = pokemon_possibles_stats.iloc[0]

best_pokemon

pokemon_id    150
stat_id         4
base_stat     154
effort          3
Name: 897, dtype: int64